version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./react-docker
    ports:
      - "8080:8080"
    volumes:
      - ./react-docker:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    container_name: backend
    build: ./node-docker
    ports:
      - "8000:8000"
    volumes:
      - ./node-docker:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development